#!/usr/bin/env node
/**
 * ARES Setup Script
 * Automatically configures the project for first-time users
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  red: '\x1b[31m',
};

function log(message, color = colors.reset) {
  console.log(`${color}${message}${colors.reset}`);
}

function header(text) {
  console.log('\n' + '='.repeat(60));
  log(`  ${text}`, colors.bright + colors.blue);
  console.log('='.repeat(60) + '\n');
}

function success(text) {
  log(`✅ ${text}`, colors.green);
}

function warning(text) {
  log(`⚠️  ${text}`, colors.yellow);
}

function error(text) {
  log(`❌ ${text}`, colors.red);
}

function runCommand(command, description) {
  log(`▶️  ${description}...`, colors.blue);
  try {
    execSync(command, { stdio: 'inherit' });
    success(`${description} completed`);
    return true;
  } catch (err) {
    error(`${description} failed`);
    return false;
  }
}

function ensureDirectory(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
    success(`Created directory: ${dirPath}`);
  }
}

function setupEnvironment() {
  header('Step 1: Environment Configuration');
  
  const envPath = path.join(process.cwd(), '.env.local');
  const envExamplePath = path.join(process.cwd(), '.env.example');
  
  if (fs.existsSync(envPath)) {
    warning('.env.local already exists. Skipping...');
    return;
  }
  
  if (!fs.existsSync(envExamplePath)) {
    error('.env.example not found!');
    process.exit(1);
  }
  
  // Create .env.local from .env.example
  const envContent = `# ARES Environment Configuration
# Auto-generated by setup script

# Database Configuration (SQLite)
DATABASE_URL="file:./prisma/dev.db"

# JWT Secret (Change this in production!)
JWT_SECRET="${generateRandomSecret()}"

# Node Environment
NODE_ENV="development"
`;
  
  fs.writeFileSync(envPath, envContent);
  success('Created .env.local with secure defaults');
}

function generateRandomSecret() {
  return require('crypto').randomBytes(32).toString('hex');
}

function setupDatabase() {
  header('Step 2: Database Setup');
  
  ensureDirectory(path.join(process.cwd(), 'data'));
  ensureDirectory(path.join(process.cwd(), 'prisma'));
  
  // Generate Prisma Client
  if (!runCommand('npx prisma generate', 'Generate Prisma Client')) {
    process.exit(1);
  }
  
  // Push schema to database
  if (!runCommand('npx prisma db push --accept-data-loss', 'Initialize database schema')) {
    process.exit(1);
  }
}

function seedDatabase() {
  header('Step 3: Seed Initial Data');
  
  if (!runCommand('npx prisma db seed', 'Seed database with initial skills')) {
    warning('Seeding failed, but you can run it manually later with: npm run db:seed');
  }
}

function printSuccess() {
  console.log('\n' + '='.repeat(60));
  log('  🎉 ARES Setup Complete!', colors.bright + colors.green);
  console.log('='.repeat(60) + '\n');
  
  log('Next steps:', colors.bright);
  console.log('  1. Review your .env.local file');
  console.log('  2. Run: npm run dev');
  console.log('  3. Open: http://localhost:3000\n');
  
  log('Useful commands:', colors.bright);
  console.log('  npm run dev       - Start development server');
  console.log('  npm run build     - Build for production');
  console.log('  npm run db:studio - Open Prisma Studio (database GUI)');
  console.log('  npm run db:seed   - Re-seed database\n');
}

// Main execution
async function main() {
  console.clear();
  header('🚀 ARES Project Setup');
  
  try {
    setupEnvironment();
    setupDatabase();
    seedDatabase();
    printSuccess();
  } catch (err) {
    error('Setup failed: ' + err.message);
    process.exit(1);
  }
}

main();
